export let navbar = [
    {
        "role":"user",
        "name":"Home",
        "link":"/home",
    },
    {
        "role":"user",
        "name":"Forums",
        "link":"/forum",
    },
    {
        "role":"user",
        "name":"Blogs",
        "link":"/updates",
    },
    {
        "role":"user",
        "name":"Community",
        "link":"/community",
    },
]